SOURCES += src/sntp/sntp.c \
src/sntp/time.c \
src/memory/sd_spi.c \
src/memory/sd_test.c \
src/memory/checksum.c \
src/memory/write.c \
src/memory/memory.c \
src/memory/sd.c \
src/net_init_service.c \
src/http_rx.c \
src/debug.c \
src/frame_processor.c \
src/radio/radio_irq.c \
src/radio/ieee_frame.c \
src/radio/rf212_functions.c \
src/radio/radio.c \
src/radio/rf212.c \
src/radio/radio_functions.c \
src/main.c \
src/radio_init_service.c \
src/upload.c \
src/server_tcp.c \
src/console.c \
src/base64.c \
src/http_tx.c \
src/lwip/arch/lpc_arch_systick.c \
src/lwip/arch/lpc_debug.c \
src/lwip/arch/sys_arch.c \
src/lwip/core/tcp_out.c \
src/lwip/core/init.c \
src/lwip/core/udp.c \
src/lwip/core/dns.c \
src/lwip/core/timers.c \
src/lwip/core/sys.c \
src/lwip/core/memp.c \
src/lwip/core/stats.c \
src/lwip/core/mem.c \
src/lwip/core/snmp/asn1_enc.c \
src/lwip/core/snmp/msg_in.c \
src/lwip/core/snmp/msg_out.c \
src/lwip/core/snmp/mib_structs.c \
src/lwip/core/snmp/mib2.c \
src/lwip/core/snmp/asn1_dec.c \
src/lwip/core/def.c \
src/lwip/core/ipv4/inet_chksum.c \
src/lwip/core/ipv4/icmp.c \
src/lwip/core/ipv4/ip_addr.c \
src/lwip/core/ipv4/autoip.c \
src/lwip/core/ipv4/ip.c \
src/lwip/core/ipv4/inet.c \
src/lwip/core/ipv4/ip_frag.c \
src/lwip/core/ipv4/igmp.c \
src/lwip/core/tcp.c \
src/lwip/core/tcp_in.c \
src/lwip/core/raw.c \
src/lwip/core/dhcp.c \
src/lwip/core/pbuf.c \
src/lwip/core/netif.c \
src/lwip/netif/ppp/lcp.c \
src/lwip/netif/ppp/auth.c \
src/lwip/netif/ppp/magic.c \
src/lwip/netif/ppp/pap.c \
src/lwip/netif/ppp/fsm.c \
src/lwip/netif/ppp/chpms.c \
src/lwip/netif/ppp/md5.c \
src/lwip/netif/ppp/ipcp.c \
src/lwip/netif/ppp/ppp_oe.c \
src/lwip/netif/ppp/randm.c \
src/lwip/netif/ppp/ppp.c \
src/lwip/netif/ppp/vj.c \
src/lwip/netif/ppp/chap.c \
src/lwip/netif/etharp.c \
src/lwip/netif/lpc_phy_dp83848.c \
src/lwip/netif/slipif.c \
src/lwip/netif/lpc_phy_lan8720.c \
src/lwip/netif/lpc_emac_zcbuffs.c \
src/lwip/netif/lpc_mac_addr.c \
src/lwip/netif/mac_addr_i2c.c \
src/lwip/netif/lpc_emac.c \
src/lwip/api/netdb.c \
src/lwip/api/err.c \
src/lwip/api/api_lib.c \
src/lwip/api/netbuf.c \
src/lwip/api/sockets.c \
src/lwip/api/netifapi.c \
src/lwip/api/api_msg.c \
src/lwip/api/tcpip.c \
src/clocking.c \
